# Generated by Django 5.0.3 on 2024-03-06 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otpa', '0002_unit_examcard_year_of_study_student_profile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otprecord',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='otpa.department'),
        ),
        migrations.AddField(
            model_name='otprecord',
            name='units',
            field=models.ManyToManyField(to='otpa.unit'),
        ),
        migrations.AddField(
            model_name='otprecord',
            name='year_of_study',
            field=models.PositiveIntegerField(default=1),
        ),
    
    ]
