# Generated by Django 5.0.3 on 2024-03-08 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otpa', '0004_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examcard',
            name='year_of_study',
            field=models.PositiveIntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='otprecord',
            name='year_of_study',
            field=models.PositiveIntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='otpa.department'),
        ),
    ]
