# Generated by Django 5.0.3 on 2024-03-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otpa', '0005_alter_examcard_year_of_study_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examcard',
            name='exam_photo',
            field=models.ImageField(blank=True, null=True, upload_to='exam_photos/'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
