# Generated by Django 5.0.3 on 2024-03-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otpa', '0009_alter_examcard_exam_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examcard',
            name='exam_photo',
            field=models.ImageField(null=True, upload_to='exam_photos/'),
        ),
    ]
