# Generated by Django 5.0.3 on 2024-03-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otpa', '0010_alter_examcard_exam_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(null=True, upload_to='logo/')),
            ],
        ),
    ]
