# Generated by Django 5.0.2 on 2024-05-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otpa', '0011_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examcard',
            name='otp_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
