# Generated by Django 5.0.2 on 2024-05-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otpa', '0012_alter_examcard_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examcard',
            name='year_of_study',
            field=models.PositiveIntegerField(blank=True, default=2024, null=True),
        ),
    ]
